export { default as H1 } from './H1.astro';
export { default as H2 } from './H2.astro';
export { default as H3 } from './H3.astro';
export { default as H4 } from './H4.astro';
export { default as P } from './P.astro';
export { default as Ul } from './Ul.astro';
export { default as Blockquote } from './Blockquote.astro';
export { default as InlineCode } from './InlineCode.astro';
export { default as Table } from './Table.astro';